# -*- coding: utf-8 -*-
"""Airline Data Visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yOUSCvlOcklJqUG9Gi8eTxF5mARliAGR
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load dataset
df = pd.read_csv("./Airlines.csv")

# Display basic info about dataset
print("Dataset Info:")
df.info()
print("\nSummary Statistics:")
print(df.describe())

# Check for missing values
print("\nMissing Values:")
print(df.isnull().sum())

# Plot distribution of Delay variable
plt.figure(figsize=(8,5))
sns.countplot(x=df['Delay'])
plt.title("Distribution of Delays")
plt.xlabel("Delayed (1) vs Not Delayed (0)")
plt.ylabel("Count")
plt.show()

# Airline-wise Delay Analysis
plt.figure(figsize=(12,6))
df.groupby('Airline')['Delay'].mean().sort_values().plot(kind='bar')
plt.title("Average Delay Rate by Airline")
plt.xlabel("Airline")
plt.ylabel("Average Delay Rate")
plt.show()

# Airport-wise Delay Analysis
plt.figure(figsize=(12,6))
df.groupby('AirportFrom')['Delay'].mean().sort_values().tail(20).plot(kind='bar')
plt.title("Top 20 Airports with Highest Delay Rates")
plt.xlabel("Airport")
plt.ylabel("Average Delay Rate")
plt.show()

# Departure Time vs Delays
plt.figure(figsize=(12,6))
sns.histplot(df, x='Time', hue='Delay', bins=24, kde=True)
plt.title("Impact of Departure Time on Delays")
plt.xlabel("Time of Day (Minutes Past Midnight)")
plt.ylabel("Number of Flights")
plt.show()

# Flight Length vs Delay Probability
plt.figure(figsize=(8,5))
sns.boxplot(x=df['Delay'], y=df['Length'])
plt.title("Flight Length vs Delay Probability")
plt.xlabel("Delayed (1) vs Not Delayed (0)")
plt.ylabel("Flight Length (Minutes)")
plt.show()

# Day of the Week vs Delay Analysis
plt.figure(figsize=(10,5))
df.groupby('DayOfWeek')['Delay'].mean().plot(kind='bar')
plt.title("Delay Rate by Day of the Week")
plt.xlabel("Day of Week (1=Monday, 7=Sunday)")
plt.ylabel("Average Delay Rate")
plt.show()

# Correlation Heatmap
df_encoded = pd.get_dummies(df, columns=['Airline', 'AirportFrom', 'AirportTo'])
plt.figure(figsize=(8,6))
sns.heatmap(df_encoded.corr(), annot=True, cmap='coolwarm', fmt='.2f')
plt.title("Feature Correlation Heatmap")
plt.show()